// TODO: Support enharmonicity

export const tet24schema = {
  name: "24 TET",
  description: "Standard 24-tone equal temperament.",
  source: "https://en.wikipedia.org/wiki/Quarter_tone#Quarter-tone_scale",
  referenceName: "A",
  referencePitch: 440,
  referenceOctave: 4,
  octaveBaseName: "C",
  notes: {
    C: ["C", 0],
    "C+": ["C", 50],
    "C#": ["C+", 50],
    "C#+": ["C#", 50],
    D: ["C#+", 50],
    "D+": ["D", 50],
    "D#": ["D+", 50],
    "D#+": ["D#", 50],
    E: ["D#+", 50],
    "E+": ["E", 50],
    F: ["E+", 50],
    "F+": ["F", 50],
    "F#": ["F+", 50],
    "F#+": ["F#", 50],
    G: ["F#+", 50],
    "G+": ["G", 50],
    "G#": ["G+", 50],
    "G#+": ["G#", 50],
    A: ["G#+", 50],
    "A+": ["A", 50],
    "A#": ["A+", 50],
    "A#+": ["A#", 50],
    B: ["A#+", 50],
    "B+": ["B", 50],
  },
};

// TODO: Support enharmonicity

export const tet16schema = {
  name: "16 TET",
  description: "Standard 16-tone equal temperament.",
  source: "https://en.xen.wiki/w/16edo",
  referenceName: "A",
  referencePitch: 440,
  referenceOctave: 4,
  octaveBaseName: "D",
  notes: {
    D: ["D", 0],
    "D#": ["D", 75],
    // Eb: ["D", 75],
    E: ["D", 150],
    "E#": ["D#", 225],
    Fb: ["D", 300],
    F: ["D", 375],
    "F#": ["D", 450],
    // Gb: ["D", 450],
    G: ["D", 525],
    "G#": ["D", 600],
    // Ab: ["D", 600],
    A: ["D", 675],
    "A#": ["D", 750],
    // Bb: ["D", 750],
    B: ["D", 825],
    "B#": ["D", 900],
    Cb: ["D", 975],
    C: ["D", 1050],
    "C#": ["D", 1125],
    // Db: ["D", 1125],
  },
};

// TODO: Support enharmonicity

export const tet17schema = {
  name: "17 TET",
  description: "Standard 17-tone equal temperament.",
  source: "https://en.xen.wiki/w/17edo",
  referenceName: "A",
  referencePitch: 440,
  referenceOctave: 4,
  octaveBaseName: "D",
  // temperament.js has a bug in the check to see if a note has been defined conflictually--Math.round workaround
  notes: {
    D: ["D", 0],
    Eb: ["D", Math.round(70.59)],
    // "D+": ["D", Math.round(70.59)],
    "D#": ["D", Math.round(141.18)],
    // Ed: ["D", Math.round(141.18)],
    E: ["D", Math.round(211.76)],
    F: ["D", Math.round(282.35)],
    // Gb: ["D", Math.round(352.94)],
    "F+": ["D", Math.round(352.94)],
    "F#": ["D", Math.round(423.53)],
    // "G-": ["D", Math.round(423.53)],
    G: ["D", Math.round(494.12)],
    // Ab: ["D", Math.round(564.71)],
    "G+": ["D", Math.round(564.71)],
    "G#": ["D", Math.round(635.29)],
    // "A-": ["D", Math.round(635.29)],
    A: ["D", Math.round(705.88)],
    // Bb: ["D", Math.round(776.47)],
    "A+": ["D", Math.round(776.47)],
    "A#": ["D", Math.round(847.06)],
    // "B-": ["D", Math.round(847.06)],
    B: ["D", Math.round(917.65)],
    C: ["D", Math.round(988.24)],
    // Db: ["D", Math.round(1058.82)],
    "C+": ["D", Math.round(1058.82)],
    "C#": ["D", Math.round(1129.41)],
    // "D-": ["D", Math.round(1129.41)],
  },
};
